## Linear Regression from scratch in tensorflow

In [2]:
# import the required libs
import tensorflow as tf
import numpy

## Creating a sample Database

In [3]:
#training Dataset
X=tf.constant(range(10),dtype=tf.float32)
Y=2 * X + 10

print(X)
print(Y)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)
tf.Tensor([10. 12. 14. 16. 18. 20. 22. 24. 26. 28.], shape=(10,), dtype=float32)


In [4]:
#testing dataset 
X_test=tf.constant(range(10,20),dtype=tf.float32)
Y_test=2*X_test+10

print(X_test)
print(Y_test)

tf.Tensor([10. 11. 12. 13. 14. 15. 16. 17. 18. 19.], shape=(10,), dtype=float32)
tf.Tensor([30. 32. 34. 36. 38. 40. 42. 44. 46. 48.], shape=(10,), dtype=float32)


## Loss function

In [5]:
y_mean=Y.numpy().mean()

def predict_mean(X):
    y_hat=[y_mean] *len(X)
    return y_hat
    
Y_hat=predict_mean(X_test)    

### This value for the MSE loss above will give us a baseline to compare how a more complex model is doing

In [6]:

errors=(Y_hat-Y)**2
loss=tf.reduce_mean(errors)
loss.numpy()

33.0

In [7]:
def loss_mse(X,Y,w0,w1):
    Y_hat=w0*X+w1
    errors=(Y_hat-Y)**2
    return tf.reduce_mean(errors)

## Compute Gradients

In [8]:
def compute_gradients(X,Y,w0,w1):
    with tf.GradientTape() as tape:
        loss=loss_mse(X,Y,w0,w1)
    return tape.gradient(loss,[w0,w1])


In [13]:
w0=tf.Variable(0.0)
w1=tf.Variable(0.0)
dw0,dw1=compute_gradients(X,Y,w0,w1)

In [15]:
STEPS=1000
LEARNING_RATE=0.02
MSG='STEP {step}- loss:{loss},w0:{w0},w1:{w1}\n'
w0=tf.Variable(0.0)
w1=tf.Variable(0.0)
for step in range(0,STEPS+1):
    dw0,dw1=compute_gradients(X,Y,w0,w1)
    w0.assign_sub(dw0*LEARNING_RATE)
    w1.assign_sub(dw1*LEARNING_RATE)

    if step%100 ==0:
        loss=loss_mse(X,Y,w0,w1)
        print(MSG.format(step=step,loss=loss,w0=w0.numpy(),w1=w1.numpy()))
        

        


STEP 0- loss:35.70719528198242,w0:4.079999923706055,w1:0.7599999904632568

STEP 100- loss:2.6017532348632812,w0:2.4780430793762207,w1:7.002389907836914

STEP 200- loss:0.26831889152526855,w0:2.153517961502075,w1:9.037351608276367

STEP 300- loss:0.027671903371810913,w0:2.0493006706237793,w1:9.690855979919434

STEP 400- loss:0.0028539239428937435,w0:2.0158326625823975,w1:9.90071964263916

STEP 500- loss:0.0002943490108009428,w0:2.005084753036499,w1:9.96811580657959

STEP 600- loss:3.0356444767676294e-05,w0:2.0016329288482666,w1:9.989760398864746

STEP 700- loss:3.1322738323069643e-06,w0:2.0005245208740234,w1:9.996710777282715

STEP 800- loss:3.2238213520940917e-07,w0:2.0001683235168457,w1:9.998944282531738

STEP 900- loss:3.369950718479231e-08,w0:2.000054359436035,w1:9.999658584594727

STEP 1000- loss:3.6101481803996194e-09,w0:2.0000178813934326,w1:9.99988842010498



In [16]:
loss=loss_mse(X_test,Y_test,w0,w1)
loss.numpy()

2.4563633e-08